# Generated by Django 6.0 on 2026-01-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.TextField()),
                ('postal_code', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('physical_stock', models.IntegerField()),
                ('available_stock', models.IntegerField()),
                ('pictureUrl', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('WAITING_PAYMENT', 'Waiting Payment'), ('TO_BE_PREPARED', 'To Be Prepared'), ('SHIPPED', 'Shipped'), ('CANCELED', 'Canceled'), ('ERROR', 'Error')], default='WAITING_PAYMENT', max_length=20)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='domain.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.product')),
            ],
        ),
    ]
