# Generated by Django 6.0 on 2026-01-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_shopifyproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyconfig',
            name='location_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
