# Generated by Django 6.0 on 2026-01-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_shopifyconfig_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_order_id', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.shopifyconfig')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('config', 'order'), name='unique_shopify_order_link')],
            },
        ),
    ]
